#!/bin/bash
#curl https://raw.githubusercontent.com/jua74470/odiniptvpanelfreesourcecode/installer/install/docker/CentOS/6/build.sh -o /root/build.sh && bash /root/build.sh
curl https://raw.githubusercontent.com/jua74470/odiniptvpanelfreesourcecode/installer/install/docker/CentOS/6/CentOS-Base.repo -o /etc/yum.repos.d/CentOS-Base.repo
rm -f /etc/yum.repos.d/CentOS-Debuginfo.repo /etc/yum.repos.d/CentOS-Media.repo /etc/yum.repos.d/CentOS-Vault.repo /etc/yum.repos.d/CentOS-fasttrack.repo
yum -y update
yum -y install @core
yum -y install epel-release
yum -y update
yum -y install http://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-6.noarch.rpm http://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-6.noarch.rpm
yum -y install https://rpms.remirepo.net/enterprise/remi-release-6.rpm
yum install -y https://extras.getpagespeed.com/release-latest.rpm
yum install -y curl
yum clean all
yum -y update
yum --setopt=metadata_expire=never install -y @core
yum --setopt=metadata_expire=never install -y dnf-plugins-core
#yum config-manager --set-enabled remi
#yum config-manager --set-enabled rpmfusion-free
#yum config-manager --set-enabled rpmfusion-nonfree
yum --setopt=metadata_expire=never install -y libicu-devel
yum --setopt=metadata_expire=never install -y tzdata
yum --setopt=metadata_expire=never install -y openssh-server
yum --setopt=metadata_expire=never install -y sudo
yum --setopt=metadata_expire=never install -y vim
yum --setopt=metadata_expire=never install -y make
yum --setopt=metadata_expire=never install -y zip
yum --setopt=metadata_expire=never install -y unzip
yum --setopt=metadata_expire=never install -y chkconfig
yum --setopt=metadata_expire=never install -y bash-completion
yum --setopt=metadata_expire=never install -y wget
yum --setopt=metadata_expire=never install -y bzip2-libs
yum --setopt=metadata_expire=never install -y curl-devel
yum --setopt=metadata_expire=never install -y libcurl-devel
yum --setopt=metadata_expire=never install -y perl-libwww-perl
yum --setopt=metadata_expire=never install -y libxml2
yum --setopt=metadata_expire=never install -y libxml2-devel
yum --setopt=metadata_expire=never install -y bzip2-devel
yum --setopt=metadata_expire=never install -y gcc
yum --setopt=metadata_expire=never install -y gcc-c++
yum --setopt=metadata_expire=never install -y autoconf
yum --setopt=metadata_expire=never install -y automake
yum --setopt=metadata_expire=never install -y libtool
yum --setopt=metadata_expire=never install -y libtool-ltdl-devel
yum --setopt=metadata_expire=never install -y git-core
yum --setopt=metadata_expire=never install -y systemtap-sdt-devel
yum --setopt=metadata_expire=never install -y procps
yum --setopt=metadata_expire=never install -y at
yum --setopt=metadata_expire=never install -y ca-certificates
yum --setopt=metadata_expire=never install -y nano
yum --setopt=metadata_expire=never install -y psmisc
yum --setopt=metadata_expire=never install -y daemonize
yum --setopt=metadata_expire=never install -y jq
yum --setopt=metadata_expire=never install -y sshpass
yum --setopt=metadata_expire=never install -y net-tools
yum --setopt=metadata_expire=never install -y e2fsprogs
yum --setopt=metadata_expire=never install -y e2fsprogs-devel
yum --setopt=metadata_expire=never install -y e2fsprogs-libs
yum --setopt=metadata_expire=never install -y e2fsprogs-static
yum --setopt=metadata_expire=never install -y libxslt-devel
yum --setopt=metadata_expire=never install -y GeoIP-devel
yum --setopt=metadata_expire=never install -y GeoIP-*
yum --setopt=metadata_expire=never install -y htop
yum --setopt=metadata_expire=never install -y httpd
yum --setopt=metadata_expire=never install -y httpd-devel
yum --setopt=metadata_expire=never install -y mc
yum --setopt=metadata_expire=never install -y libpng-devel
yum --setopt=metadata_expire=never install -y mcrypt
yum --setopt=metadata_expire=never install -y libmcrypt-devel
yum --setopt=metadata_expire=never install -y libmaxminddb-devel
yum --setopt=metadata_expire=never install -y libX11-devel
yum --setopt=metadata_expire=never install -y zlib-devel
yum --setopt=metadata_expire=never install -y gnupg2
yum --setopt=metadata_expire=never install -y gnupg
yum --setopt=metadata_expire=never install -y pam-devel
yum --setopt=metadata_expire=never install -y pam
yum --setopt=metadata_expire=never install -y nginx
yum --setopt=metadata_expire=never install -y nginx-devel
yum --setopt=metadata_expire=never install -y libstdc++-devel
yum --setopt=metadata_expire=never install -y openssl-devel
yum --setopt=metadata_expire=never install -y sqlite-devel
yum --setopt=metadata_expire=never install -y zlib-devel
yum --setopt=metadata_expire=never install -y smtpdaemon
yum --setopt=metadata_expire=never install -y libedit-devel
yum --setopt=metadata_expire=never install -y pcre-devel
yum --setopt=metadata_expire=never install -y pcre2-devel
yum --setopt=metadata_expire=never install -y libxcrypt-devel
yum --setopt=metadata_expire=never install -y perl-interpreter
yum --setopt=metadata_expire=never install -y libacl-devel
yum --setopt=metadata_expire=never install -y systemd-devel
yum --setopt=metadata_expire=never install -y krb5-devel
yum --setopt=metadata_expire=never install -y libc-client-devel
yum --setopt=metadata_expire=never install -y cyrus-sasl-devel
yum --setopt=metadata_expire=never install -y openldap-devel
yum --setopt=metadata_expire=never install -y libpq-devel
yum --setopt=metadata_expire=never install -y unixODBC-devel
yum --setopt=metadata_expire=never install -y firebird-devel
yum --setopt=metadata_expire=never install -y net-snmp-devel
yum --setopt=metadata_expire=never install -y oniguruma-devel
yum --setopt=metadata_expire=never install -y gd-devel gmp-devel
yum --setopt=metadata_expire=never install -y db4-devel
yum --setopt=metadata_expire=never install -y tokyocabinet-devel
yum --setopt=metadata_expire=never install -y lmdb-devel
yum --setopt=metadata_expire=never install -y qdbm-devel
yum --setopt=metadata_expire=never install -y libtidy-devel
yum --setopt=metadata_expire=never install -y freetds-devel
yum --setopt=metadata_expire=never install -y aspell-devel
yum --setopt=metadata_expire=never install -y enchant-devel
yum --setopt=metadata_expire=never install -y libenchant-devel
yum --setopt=metadata_expire=never install -y libsodium-devel
yum --setopt=metadata_expire=never install -y sodium-devel
yum --setopt=metadata_expire=never install -y libffi-devel
yum --setopt=metadata_expire=never install -y ffi-devel
yum --setopt=metadata_expire=never install -y xslt-devel
yum --setopt=metadata_expire=never install -y yasm
yum --setopt=metadata_expire=never install -y nasm
yum --setopt=metadata_expire=never install -y gnutls-devel
yum --setopt=metadata_expire=never install -y ass-devel
yum --setopt=metadata_expire=never install -y librtmp-devel
yum --setopt=metadata_expire=never install -y librtmp
yum --setopt=metadata_expire=never install -y rtmp-devel
yum --setopt=metadata_expire=never install -y rtmp
yum --setopt=metadata_expire=never install -y rtmpdump
yum --setopt=metadata_expire=never install -y alsa-lib-devel
yum --setopt=metadata_expire=never install -y AMF-devel
yum --setopt=metadata_expire=never install -y flite-devel
yum --setopt=metadata_expire=never install -y fontconfig-devel
yum --setopt=metadata_expire=never install -y freetype-devel
yum --setopt=metadata_expire=never install -y fribidi-devel
yum --setopt=metadata_expire=never install -y frei0r-devel
yum --setopt=metadata_expire=never install -y game-music-emu-devel
yum --setopt=metadata_expire=never install -y gsm-devel
yum --setopt=metadata_expire=never install -y ilbc-devel
yum --setopt=metadata_expire=never install -y jack-audio-connection-kit-devel
yum --setopt=metadata_expire=never install -y ladspa-devel
yum --setopt=metadata_expire=never install -y libaom-devel
yum --setopt=metadata_expire=never install -y libdav1d-devel
yum --setopt=metadata_expire=never install -y libass-devel
yum --setopt=metadata_expire=never install -y libbluray-devel
yum --setopt=metadata_expire=never install -y libbs2b-devel
yum --setopt=metadata_expire=never install -y libcaca-devel
yum --setopt=metadata_expire=never install -y libcdio-paranoia-devel
yum --setopt=metadata_expire=never install -y libchromaprint-devel
yum --setopt=metadata_expire=never install -y libcrystalhd-devel
yum --setopt=metadata_expire=never install -y lensfun-devel
yum --setopt=metadata_expire=never install -y libavc1394-devel
yum --setopt=metadata_expire=never install -y libdc1394-devel
yum --setopt=metadata_expire=never install -y libiec61883-devel
yum --setopt=metadata_expire=never install -y libdrm-devel
yum --setopt=metadata_expire=never install -y libgcrypt-devel
yum --setopt=metadata_expire=never install -y libGL-devel
yum --setopt=metadata_expire=never install -y libmodplug-devel
yum --setopt=metadata_expire=never install -y libmysofa-devel
yum --setopt=metadata_expire=never install -y libopenmpt-devel
yum --setopt=metadata_expire=never install -y librsvg2-devel
yum --setopt=metadata_expire=never install -y libsmbclient-devel
yum --setopt=metadata_expire=never install -y libssh-devel
yum --setopt=metadata_expire=never install -y libtheora-devel
yum --setopt=metadata_expire=never install -y libv4l-devel
yum --setopt=metadata_expire=never install -y libva-devel
yum --setopt=metadata_expire=never install -y libvdpau-devel
yum --setopt=metadata_expire=never install -y vapoursynth-devel
yum --setopt=metadata_expire=never install -y libvpx-devel
yum --setopt=metadata_expire=never install -y libmfx mfx
yum --setopt=metadata_expire=never install -y libmfx-devel
yum --setopt=metadata_expire=never install -y nasm libwebp-devel
yum --setopt=metadata_expire=never install -y netcdf-devel
yum --setopt=metadata_expire=never install -y raspberrypi-vc-devel
yum --setopt=metadata_expire=never install -y nv-codec-headers
yum --setopt=metadata_expire=never install -y opencore-amr-devel
yum --setopt=metadata_expire=never install -y vo-amrwbenc-devel
yum --setopt=metadata_expire=never install -y libomxil-bellagio-devel
yum --setopt=metadata_expire=never install -y libxcb-devel
yum --setopt=metadata_expire=never install -y lilv-devel
yum --setopt=metadata_expire=never install -y lv2-devel
yum --setopt=metadata_expire=never install -y openal-soft-devel
yum --setopt=metadata_expire=never install -y opencl-headers
yum --setopt=metadata_expire=never install -y ocl-icd-devel
yum --setopt=metadata_expire=never install -y openjpeg2-devel
yum --setopt=metadata_expire=never install -y pulseaudio-libs-devel
yum --setopt=metadata_expire=never install -y podman
yum --setopt=metadata_expire=never install -y rav1e-devel
yum --setopt=metadata_expire=never install -y rubberband-devel
yum --setopt=metadata_expire=never install -y SDL2-devel
yum --setopt=metadata_expire=never install -y snappy-devel
yum --setopt=metadata_expire=never install -y soxr-devel
yum --setopt=metadata_expire=never install -y speex-devel
yum --setopt=metadata_expire=never install -y srt-devel
yum --setopt=metadata_expire=never install -y srt-libs
yum --setopt=metadata_expire=never install -y srt-lib
yum --setopt=metadata_expire=never install -y srt
yum --setopt=metadata_expire=never install -y svt-av1-devel
yum --setopt=metadata_expire=never install -y tesseract-devel
yum --setopt=metadata_expire=never install -y texi2html
yum --setopt=metadata_expire=never install -y texinfo
yum --setopt=metadata_expire=never install -y twolame-devel
yum --setopt=metadata_expire=never install -y libvmaf-devel
yum --setopt=metadata_expire=never install -y wavpack-devel
yum --setopt=metadata_expire=never install -y vid.stab-devel
yum --setopt=metadata_expire=never install -y vulkan-loader-devel
yum --setopt=metadata_expire=never install -y libshaderc-devel
yum --setopt=metadata_expire=never install -y libshaderc
yum --setopt=metadata_expire=never install -y spirv-tools-libs
yum --setopt=metadata_expire=never install -y zimg-devel
yum --setopt=metadata_expire=never install -y zlib-devel
yum --setopt=metadata_expire=never install -y zeromq-devel
yum --setopt=metadata_expire=never install -y zvbi-devel
yum --setopt=metadata_expire=never install -y vmaf-models
yum --setopt=metadata_expire=never install -y pkgconfig
yum --setopt=metadata_expire=never install -y libunistring-devel
yum --setopt=metadata_expire=never install -y unistring-devel
yum --setopt=metadata_expire=never install -y libunistring
yum --setopt=metadata_expire=never install -y unistring
yum --setopt=metadata_expire=never install -y re2c
yum --setopt=metadata_expire=never install -y perl
yum --setopt=metadata_expire=never install -y debhelper
yum --setopt=metadata_expire=never install -y cdbs
yum --setopt=metadata_expire=never install -y lintian
yum --setopt=metadata_expire=never install -y fakeroot
yum --setopt=metadata_expire=never install -y devscripts
yum --setopt=metadata_expire=never install -y dh-make
yum --setopt=metadata_expire=never install -y dput
yum --setopt=metadata_expire=never install -y pbuilder
yum --setopt=metadata_expire=never install -y debootstrap
yum --setopt=metadata_expire=never install -y apt
yum --setopt=metadata_expire=never install -y dpkg
yum --setopt=metadata_expire=never install -y perl-macros
yum --setopt=metadata_expire=never install -y perl-srpm-macros
